version: '3.9'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        container_name: xzs-backend
        restart: always
        ports: 
            - 8000:8000
        environment:
            SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.1.7:30432/postgres"
            SPRING_DATASOURCE_USERNAME: "dev"
            SPRING_DATASOURCE_PASSWORD: "passw0rd_dev"
            SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
            SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"

    frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        container_name: xzs-frontend
        restart: always
        ports:
            - 80:80
        depends_on:
            - backend